# Generated by Django 4.1.6 on 2023-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(default='Tutor', max_length=200),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='Person', max_length=200),
        ),
    ]
