# Generated by Django 4.1.6 on 2023-04-05 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionreplies',
            name='reply_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 5, 21, 3, 54, 247965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 5, 21, 3, 54, 247167, tzinfo=datetime.timezone.utc)),
        ),
    ]
