# Generated by Django 4.1.6 on 2023-04-05 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_discussionreplies_reply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discussionreplies',
            name='reply_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 5, 21, 30, 1, 927352, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 5, 21, 30, 1, 926635, tzinfo=datetime.timezone.utc)),
        ),
    ]
