# Generated by Django 4.1.6 on 2023-03-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sessionrequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
