# Generated by Django 4.1.6 on 2023-04-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment'),
        ('myapp', '0002_remove_tutor_review'),
    ]

    operations = [
    ]
