# Generated by Django 4.1.6 on 2023-04-05 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tutor_slug_alter_discussionreplies_reply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionreplies',
            name='reply_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 5, 22, 5, 4, 661582, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 5, 22, 5, 4, 660818, tzinfo=datetime.timezone.utc)),
        ),
    ]
