# Generated by Django 4.1.6 on 2023-04-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_0002_appointment_0002_remove_tutor_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='session',
        ),
    ]
