# Generated by Django 4.1.6 on 2023-03-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_student_user_remove_tutor_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursenum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='service',
            field=models.CharField(choices=[('1', 'General subject review'), ('2', 'Homework/Practice problem help'), ('3', 'Exam Prep'), ('4', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Bobby', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Brown', max_length=200),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='course',
        ),
        migrations.AddField(
            model_name='tutor',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
