# Generated by Django 4.2 on 2023-04-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_review_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_name',
        ),
    ]
