# Generated by Django 4.1.7 on 2023-03-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_course_coursenum'),
        ('myapp', '0005_remove_tutor_course_tutor_course'),
    ]

    operations = [
    ]
