# Generated by Django 4.1.7 on 2023-03-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_course_coursenum"),
        ("myapp", "0006_merge_20230320_2131"),
    ]

    operations = []
