# Generated by Django 4.1.6 on 2023-03-29 03:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_merge_20230320_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='discussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('title_text', models.CharField(max_length=200, null=True)),
                ('question_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 29, 3, 31, 17, 35831, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='discussionReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('reply_text', models.CharField(max_length=500)),
                ('reply_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 3, 29, 3, 31, 17, 36137, tzinfo=datetime.timezone.utc))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.discussionthread')),
            ],
        ),
    ]
