# Generated by Django 4.1.7 on 2023-03-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_course_coursenum_alter_sessionrequest_service_and_more"),
        ("myapp", "0008_remove_course_professor"),
    ]

    operations = []
