# Generated by Django 4.1.6 on 2023-04-10 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tutor_user_alter_discussionreplies_reply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionreplies',
            name='reply_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 10, 18, 38, 50, 640904, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 10, 18, 38, 50, 640184, tzinfo=datetime.timezone.utc)),
        ),
    ]
