# Generated by Django 4.1.7 on 2023-04-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_course_professor'),
        ('myapp', '0009_alter_discussionreplies_reply_date_and_more'),
    ]

    operations = [
    ]
