# Generated by Django 4.1.6 on 2023-04-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_discussionreplies_reply_date_and_more'),
        ('myapp', '0009_merge_20230329_2203'),
    ]

    operations = [
    ]
