# Generated by Django 4.1.6 on 2023-04-10 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_discussionreplies_reply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='pending',
            field=models.IntegerField(choices=[(1, 'Confirm'), (2, 'Decline')], null=True),
        ),
        migrations.AlterField(
            model_name='discussionreplies',
            name='reply_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 10, 19, 44, 54, 822017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 4, 10, 19, 44, 54, 821368, tzinfo=datetime.timezone.utc)),
        ),
    ]
