# Generated by Django 4.1.7 on 2023-04-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_20230403_2215'),
        ('myapp', '0011_alter_discussionreplies_reply_date_and_more'),
    ]

    operations = [
    ]
