# Generated by Django 4.1.6 on 2023-04-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_course_id_alter_discussionreplies_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionreplies',
            name='reply_date',
        ),
        migrations.RemoveField(
            model_name='discussionthread',
            name='pub_date',
        ),
    ]
