# Generated by Django 4.1.6 on 2023-04-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_discussionreplies_reply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionreplies',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.discussionthread'),
        ),
    ]
