# Generated by Django 4.1.7 on 2023-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_merge_20230403_2334'),
        ('myapp', '0016_alter_discussionreplies_question'),
    ]

    operations = [
    ]
